// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhZ1VZB5AF_mbHdvEoW6E-yy57BEvj3tg',
    appId: '1:256266555391:web:497e9a070bcd61ba3e21ca',
    messagingSenderId: '256266555391',
    projectId: 'taskteacherapp',
    authDomain: 'taskteacherapp.firebaseapp.com',
    storageBucket: 'taskteacherapp.firebasestorage.app',
    measurementId: 'G-2Q1JBKCPBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQSmvWtEpDWLQl_DY0q5AI_T53h-u7NB8',
    appId: '1:256266555391:android:bbea5e62af72a64a3e21ca',
    messagingSenderId: '256266555391',
    projectId: 'taskteacherapp',
    storageBucket: 'taskteacherapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOgD6X0jxUBca8dKVSWRiAomP4BIPZPpE',
    appId: '1:256266555391:ios:fa6cfbe4f2c6390c3e21ca',
    messagingSenderId: '256266555391',
    projectId: 'taskteacherapp',
    storageBucket: 'taskteacherapp.firebasestorage.app',
    iosBundleId: 'com.devaxis.taskapp',
  );
}
